sonar.projectKey=jeremykenedy_aquarium-live
sonar.organization=jeremykenedy-12345

sonar.sources=src
sonar.tests=test
sonar.java.source=8
sonar.java.binaries=build/classes
sonar.java.test.binaries=build/test-classes
sonar.coverage.jacoco.xmlReportPaths=build/jacoco.xml
